---
title: "Comparing Coding"
author: "Emily"
date: "Sys.Date()"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytext)
library(ggplot2)
library(here)
library(janitor)
library(knitr)

#function to 
reorganize_data <- function(coder){
  #read in the files
  if(coder == "nico"){
    d <- readxl::read_xlsx(here("Data/nico_coding.xlsx"))
  } else {
    d <- read_csv(here("Data/emily_first100.csv"))
  }
  
  #filter down to the ones we coded and add indicator of who coded what
  d_clean <- d %>% 
            slice(1:100) %>% 
            mutate(coder = coder) %>% 
            clean_names()
  
  #long long long 
  d_long <- d_clean %>% 
            pivot_longer(cols = c(becoming, being, neither, both, unsure), 
                                   names_to = "code")
  
  d_long <- replace_na(d_long, list(value = 0))
  
  return(d_long)
}

nico <- reorganize_data(coder = "nico")
emily <- reorganize_data(coder = "emily")

emily <- emily %>% select(-text)

together <- full_join(nico, emily)

dist <- together %>% filter(value == 1) %>% 
        count(coder, code)

ggplot(dist, mapping = aes(x = code, y = n)) + 
      geom_bar(stat= "identity") + 
      facet_wrap(~coder) + 
      theme_minimal()
```
1. Agree Yes 
2. Agree No
3. Nico Yes Emily No 
4. Nico No Emily Yes

```{r}
#widen the data to compare by post
together_wide <- together %>% 
                 pivot_wider(id_cols = view_id,
                             names_from = c(coder, code),
                             names_sep = "_",
                             values_from = value)

#need to figure out how to do this programmatically 
together_comparison <- together_wide %>% 
                       mutate(becoming = 
                                case_when(nico_becoming == 1 & emily_becoming == 1 ~ "Agree Yes",
                                          nico_becoming == 0 & emily_becoming == 0 ~ "Agree No",
                                          nico_becoming == 1 & emily_becoming == 0 ~ "Nico Yes Emily No",
                                          nico_becoming == 0 & emily_becoming == 1 ~ "Nico No Emily Yes"),
                              being = 
                                case_when(nico_being == 1 & emily_being == 1 ~ "Agree Yes",
                                          nico_being == 0 & emily_being == 0 ~ "Agree No",
                                          nico_being == 1 & emily_being == 0 ~ "Nico Yes Emily No",
                                          nico_being == 0 & emily_being == 1 ~ "Nico No Emily Yes"),
                              neither = 
                                case_when(nico_neither == 1 & emily_neither == 1 ~ "Agree Yes",
                                          nico_neither == 0 & emily_neither == 0 ~ "Agree No",
                                          nico_neither == 1 & emily_neither == 0 ~ "Nico Yes Emily No",
                                          nico_neither == 0 & emily_neither == 1 ~ "Nico No Emily Yes"),
                              both = 
                                case_when(nico_both == 1 & emily_both == 1 ~ "Agree Yes",
                                          nico_both == 0 & emily_both == 0 ~ "Agree No",
                                          nico_both == 1 & emily_both == 0 ~ "Nico Yes Emily No",
                                          nico_both == 0 & emily_both == 1 ~ "Nico No Emily Yes"),
                              unsure = 
                                case_when(nico_unsure == 1 & emily_unsure == 1 ~ "Agree Yes",
                                          nico_unsure == 0 & emily_unsure == 0 ~ "Agree No",
                                          nico_unsure == 1 & emily_unsure == 0 ~ "Nico Yes Emily No",
                                          nico_unsure == 0 & emily_unsure == 1 ~ "Nico No Emily Yes"))

together_comparison %>% 
        pivot_longer(cols = becoming:unsure,
                     names_to = "category",
                     values_to = "agreement") %>% 
        ggplot(mapping = aes(x = agreement)) + 
        geom_bar() + facet_wrap(~category) + theme_minimal() + 
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

together_comparison %>% 
        pivot_longer(cols = becoming:unsure,
                     names_to = "category",
                     values_to = "agreement") %>% 
        ggplot(mapping = aes(x = category)) + 
        geom_bar() + facet_wrap(~agreement) + theme_minimal() + 
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

```

```{r}
together_comparison %>% 
        pivot_longer(cols = becoming:unsure,
                     names_to = "category",
                     values_to = "agreement") %>% 
        mutate(agree = if_else(agreement == "Nico Yes Emily No" | 
                         agreement == "Nico No Emily Yes", "disagree", "agree")) %>% 
      count(category, agree)
```

```{r}
together_comparison_long <- together_comparison %>% 
                            pivot_longer(cols = becoming:unsure,
                                         names_to = "category",
                                         values_to = "agreement_type") %>% 
                            mutate(agree = if_else(agreement_type == "Nico Yes Emily No" | 
                                     agreement_type == "Nico No Emily Yes", "disagree", "agree"))
                                    
comp <- together_comparison_long %>% 
      #filter(category == "becoming") %>% 
      filter(agree == "disagree") %>% 
      filter(category == "being" | category == "becoming") %>% 
      pivot_longer(cols = nico_being:emily_unsure,
                   names_to = c("coder", "code"),
                   names_pattern = "(.*)_(.*)") %>% 
      filter(value == 1)

comp %>% count(category, agreement_type, coder, code)

comp %>% filter(agreement_type == "Nico No Emily Yes" & coder == "nico") %>% 
ggplot(mapping = aes(code)) + geom_bar(position = "dodge") +
      facet_grid(rows = vars(category)) + labs(title = "Nico No Emily Yes",
                                               subtitle = "what did Nico pick instead") + 
      theme_minimal()


comp %>% filter(agreement_type == "Nico Yes Emily No" & coder == "emily") %>% 
ggplot(mapping = aes(code)) + geom_bar(position = "dodge") +
      facet_grid(rows = vars(category)) + labs(title = "Nico Yes Emily No",
                                               subtitle = "what did Emily pick instead") + 
      theme_minimal()

```


```{r}
ids <- together_comparison_long %>% 
       filter(agree == "disagree")

disagree_table <- together_wide %>% filter(view_id %in% ids$view_id)

og <- readxl::read_xlsx(here("Data/nico_coding.xlsx")) %>% select(view_id, text)

disagree_table <- left_join(disagree_table, og) %>% select(text, nico_becoming:emily_unsure)

library(DT)
datatable(disagree_table)
```

